"""Initial migration.

Revision ID: 3a945a5bb0b2
Revises: 
Create Date: 2024-06-16 16:33:46.099933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a945a5bb0b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultas',
    sa.Column('consulta_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('asunto', sa.String(length=50), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('consulta_id')
    )
    op.create_table('usuarios',
    sa.Column('usuarios_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('contraseña', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('usuarios_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('emprendimientos',
    sa.Column('emprendimiento_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('instagram', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('localidad', sa.String(length=50), nullable=True),
    sa.Column('provincia', sa.String(length=50), nullable=True),
    sa.Column('contacto', sa.String(length=50), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuarios_id'], ),
    sa.PrimaryKeyConstraint('emprendimiento_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emprendimientos')
    op.drop_table('usuarios')
    op.drop_table('consultas')
    # ### end Alembic commands ###
