"""Initial migration.

Revision ID: c72aecf650fe
Revises: 3a945a5bb0b2
Create Date: 2024-06-18 14:45:00.216454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c72aecf650fe'
down_revision = '3a945a5bb0b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emprendimientos',
    sa.Column('emprendimiento_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('instagram', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('localidad', sa.String(length=50), nullable=True),
    sa.Column('provincia', sa.String(length=50), nullable=True),
    sa.Column('contacto', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('emprendimiento_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emprendimientos')
    # ### end Alembic commands ###
